### ISSUE TITLE
Wrong merged_DT from  merge_finemapping_results()

### ISSUE THREAD

**Issue by saifulislampharma** [RajLabMSSM/echolocatoR#71] opened 2022-01-28 16:40 UTC
Hi,
I have couple of GWAS summary statisitics. I have completed running finemap_loci(). It has generated locus specific results. That is fine. Now I wanted to run codes given in Summarise vignette  (https://rajlabmssm.github.io/echolocatoR/articles/summarise_vignette.html). I set the "dataset " argument of merge_finemapping_results() to the parent folder where all the locus specific sub-folder are present. 
I ran the following code:
merged_DT <- merge_finemapping_results(dataset=dataset_dir, minimum_support=1, include_leadSNPs=T)

I notice the following things:
(1) it gives me the following error: Error in merge_finemapping_results(dataset = dataset_dir, minimum_support = 1,     include_leadSNPs = T): + No multi-finemap files found., though printing 
(2) when I print merged_DT , the "Dataset" column is Nalls23andMe_2019!!!. Though I have not that result stored in my machine.

I tried with "dataset" argument set to different dataset_dir, but merged_DT  is EXACTLY the same.

Could you please help? Thank You. 
dataset set to one finemap_loci() dir:
![Capture1](https://user-images.githubusercontent.com/3240040/151586290-3ae6378d-44ff-4b34-ae14-7962beb8c106.JPG)

dataset set to ANOTHER finemap_loci() dir:
![Capture2](https://user-images.githubusercontent.com/3240040/151586324-8a1581d9-7c50-40d9-9744-092de35eabfe.JPG)
:

**Comment by saifulislampharma** [comment] 2022-01-28 16:43
Here is the output of utils.session()

R version 4.1.2 (2021-11-01)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/sislam3/anaconda3/envs/echoR/lib/libopenblasp-r0.3.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] echolocatoR_0.1.2

loaded via a namespace (and not attached):
  [1] colorspace_2.0-2            rjson_0.2.21
  [3] ellipsis_0.3.2              class_7.3-20
  [5] biovizBase_1.42.0           htmlTable_2.4.0
  [7] XVector_0.34.0              GenomicRanges_1.46.1
  [9] base64enc_0.1-3             gld_2.6.4
 [11] dichromat_2.0-0             rstudioapi_0.13
 [13] proxy_0.4-26                bit64_4.0.5
 [15] AnnotationDbi_1.56.2        fansi_1.0.2
 [17] mvtnorm_1.1-3               xml2_1.3.3
 [19] splines_4.1.2               ggbio_1.42.0
 [21] cachem_1.0.6                rootSolve_1.8.2.3
 [23] knitr_1.37                  Formula_1.2-4
 [25] Rsamtools_2.10.0            dbplyr_2.1.1
 [27] cluster_2.1.2               png_0.1-7
 [29] graph_1.72.0                BiocManager_1.30.16
 [31] compiler_4.1.2              httr_1.4.2
 [33] backports_1.4.1             assertthat_0.2.1
 [35] Matrix_1.4-0                fastmap_1.1.0
 [37] lazyeval_0.2.2              prettyunits_1.1.1
 [39] htmltools_0.5.2             tools_4.1.2
 [41] gtable_0.3.0                glue_1.6.0
 [43] lmom_2.8                    GenomeInfoDbData_1.2.7
 [45] reshape2_1.4.4              dplyr_1.0.7
 [47] rappdirs_0.3.3              Rcpp_1.0.8
 [49] Biobase_2.54.0              vctrs_0.3.8
 [51] Biostrings_2.62.0           rtracklayer_1.54.0
 [53] xfun_0.29                   stringr_1.4.0
 [55] lifecycle_1.0.1             ensembldb_2.18.3
 [57] restfulr_0.0.13             XML_3.99-0.8
 [59] zlibbioc_1.40.0             MASS_7.3-55
 [61] scales_1.1.1                BSgenome_1.62.0
 [63] VariantAnnotation_1.40.0    ProtGenerics_1.26.0
 [65] hms_1.1.1                   MatrixGenerics_1.6.0
 [67] RBGL_1.70.0                 parallel_4.1.2
 [69] SummarizedExperiment_1.24.0 expm_0.999-6
 [71] AnnotationFilter_1.18.0     RColorBrewer_1.1-2
 [73] curl_4.3.2                  yaml_2.2.1
 [75] Exact_3.1                   memoise_2.0.1
 [77] gridExtra_2.3               ggplot2_3.3.5
 [79] biomaRt_2.50.2              rpart_4.1-15
 [81] reshape_0.8.8               latticeExtra_0.6-29
 [83] stringi_1.7.6               RSQLite_2.2.9
 [85] S4Vectors_0.32.3            BiocIO_1.4.0
 [87] e1071_1.7-9                 checkmate_2.0.0
 [89] filelock_1.0.2              GenomicFeatures_1.46.3
 [91] BiocGenerics_0.40.0         boot_1.3-28
 [93] BiocParallel_1.28.3         GenomeInfoDb_1.30.0
 [95] rlang_0.4.12                pkgconfig_2.0.3
 [97] matrixStats_0.61.0          bitops_1.0-7
 [99] lattice_0.20-45             purrr_0.3.4
[101] GenomicAlignments_1.30.0    htmlwidgets_1.5.4
[103] bit_4.0.4                   tidyselect_1.1.1
[105] GGally_2.1.2                plyr_1.8.6
[107] magrittr_2.0.1              R6_2.5.1
[109] IRanges_2.28.0              DescTools_0.99.44
[111] generics_0.1.1              Hmisc_4.6-0
[113] DelayedArray_0.20.0         DBI_1.1.2
[115] pillar_1.6.4                foreign_0.8-82
[117] survival_3.2-13             KEGGREST_1.34.0
[119] RCurl_1.98-1.5              nnet_7.3-17
[121] tibble_3.1.6                crayon_1.4.2
[123] utf8_1.2.2                  OrganismDbi_1.36.0
[125] BiocFileCache_2.2.0         jpeg_0.1-9
[127] progress_1.2.2              grid_4.1.2
[129] data.table_1.14.2           blob_1.2.2
[131] digest_0.6.29               stats4_4.1.2
[133] munsell_0.5.0

**Comment by bschilder** [comment] 2022-03-04 18:43
Hi @saifulislampharma thank you for bringing this to my attention. I think couple things are going on here. 

## 1. Unable to find files

I just went through and realized this was a typo in which I accidentally only searched for files with *.multi_finemap.csv* (an convention from older versions of `echolocatoR`). I've updated it so that it now searches now the old and the new *.Multi-finemap.tsv* conventions. Apologies for not catching this earlier.

## 2. Conflicting `merged_DT` variables

I think when the `merged_DT` fails to be constructed from the local files, an error is not thrown because of some internal tryCatch functions. Then, the dataset of the same variable name (`merged_DT`) is called instead. 

I've resolved this by renaming the `merged_DT` internal variable so echolocatoR can't confuse it with the PD dataset `merged_DT`.

Just reran with the Getting started vignette example and confirmed this gives different results than `merged_DT`

**Closed** 2022-03-16 17:58 UTC
